deploy:
	- provider: s3
		region: ap-northeast-1
		bucket: "coconut-codeploy"
		local_dir: dpl_cd_upload
		skip_cleanup: true
		on:
			branch: master
		access_key_id: $AWS_ACCESS_KEY
		secret_access_key: $AWS_SECRET_PASSWORD